Added a RAM indicator and setting to disable pause button
strato-emu/strato pull request #1
Opened 2023-05-09 22:20 UTC by QuackingCanary

Added a RAM indicator and setting to disable pause button on EmulationActivity. The RAM indicator will be shown at top left

2023-05-09 22:38 UTC, lynxnb requested changes

2023-05-09 22:38 UTC, lynxnb commented on app/src/main/java/emu/skyline/EmulationActivity.kt
> +                        ramUsage = File("/proc/self/statm").readLines()[0].split(' ')[1].toFloat() * 4096 / 1000000
Tiny comment for future readers
```suggestion
                        // We read the `VmRSS` value from the kernel
                        ramUsage = File("/proc/self/statm").readLines()[0].split(' ')[1].toFloat() * 4096 / 1000000
```

2023-05-09 22:38 UTC, lynxnb commented on app/src/main/java/emu/skyline/EmulationActivity.kt
> +                        updatePerformanceStatistics()
You don't need to call this here.

2023-05-09 22:38 UTC, lynxnb commented on app/src/main/java/emu/skyline/EmulationActivity.kt
> +            }
```suggestion
        binding.onScreenPauseToggle.apply {
            isGone = !emulationSettings.showPauseButton
        }
```

2023-05-09 23:17 UTC, lynxnb commented on app/src/main/java/emu/skyline/EmulationActivity.kt
> +                        updatePerformanceStatistics()
This is still there

2023-05-09 23:36 UTC, QuackingCanary commented on app/src/main/java/emu/skyline/EmulationActivity.kt
> +                        updatePerformanceStatistics()
How can I display the indicator to the right if I don't call ramStats here?

2023-05-09 23:44 UTC, AbandonedCart commented
`git rebase -i HEAD~3 --preserve-merges`
press the down arrow, then the `s` key
change the pick to fixup for the second and third commits
press ecape key, then type`:x` and press enter
`git push -f`

This is assuming you are using a linux or mac OS

2023-05-10 07:45 UTC, QuackingCanary commented
@AbandonedCart Thanks for your help. It says `error: cannot rebase: You have unstaged changes.`

2023-05-10 07:50 UTC, dima-xd commented
> @AbandonedCart Thanks for your help. It says `error: cannot rebase: You have unstaged changes.`. Even though I don't have anything more to commit

probably broken submodules

2023-05-10 08:05 UTC, AbandonedCart commented
`git status` will tell you what it thinks has changed

2023-05-10 19:52 UTC, AbandonedCart commented
Does this still hide the pause when going into PiP? Part of why it was linked to the controls was to automatically hide with them.

2023-05-10 19:54 UTC, QuackingCanary commented
Yes, that's the case

2023-06-07 11:12 UTC, lynxnb approved these changes
Nonetheless, code is looking good, thanks!

2023-06-26 21:43 UTC, merged