RequestSyncDeliveryCache service stub
strato-emu/strato pull request #154
Opened 2023-08-05 18:52 UTC by QuackingCanary

RequestSyncDeliveryCache service stub to get Pikmin 4 booting

2023-08-05 20:57 UTC, PabloG02 commented on app/src/main/cpp/skyline/services/bcat/IDeliveryCacheProgressService.cpp
> +// Copyright © 2023 Strato Team and Contributors (https://github.com/skyline-emu/)
```suggestion
// Copyright © 2023 Strato Team and Contributors (https://github.com/strato-emu/)
```

2023-08-07 10:44 UTC, lynxnb requested changes
Thanks! I'll merge after you squash into 1 commit.

2023-08-07 10:44 UTC, lynxnb commented on app/src/main/cpp/skyline/services/bcat/IDeliveryCacheProgressService.cpp
> +}
New line at the end of a file.

2023-08-07 10:44 UTC, lynxnb commented on app/src/main/cpp/skyline/services/bcat/IDeliveryCacheProgressService.h
> +}
New line at the end of each file.

2023-08-07 13:10 UTC, lynxnb approved these changes

2023-08-07 13:10 UTC, merged