Add support for multiple search locations
strato-emu/strato pull request #24
Opened 2023-05-18 20:20 UTC by hacobotdev

2023-05-18 21:21 UTC, Aleixz approved these changes

2023-06-07 11:06 UTC, lynxnb requested changes
Good job! There's a few details to iron out but overall the code is good.

2023-06-07 11:06 UTC, lynxnb commented on app/src/main/java/emu/skyline/utils/SearchLocationHelper.kt
> +         * @param uri The input stream to read the driver from
```suggestion
         * @param uri The uri of the search location to delete
```

2023-06-07 11:06 UTC, lynxnb commented on app/src/main/java/emu/skyline/utils/SearchLocationHelper.kt
> +            var urisArray = arrayOf<Uri?>();
Not sure why you went with `Array` here, why not use `List`? Use `mutableListOf<Uri>` here and then change the return value of this function to `List<Uri>`.

2023-07-08 00:35 UTC, closed without merging