Add basic support for google game dashboard
strato-emu/strato pull request #240
Opened 2024-01-23 10:56 UTC by QuackingCanary

Add basic support for Google Game Dashboard that allows the user to switch between performance and battery saving modes

2024-01-23 11:10 UTC, lynxnb requested changes

2024-01-23 11:10 UTC, lynxnb commented on app/src/main/AndroidManifest.xml
> +        android:appCategory="game"
This needs to be tested, it was causing weird crashes on Adreno devices.

2024-01-23 11:10 UTC, lynxnb commented on app/src/main/res/xml-v33/game_mode_config.xml
> +<?xml version="1.0" encoding="utf-8"?><!--
Add an empty new line at the end of the file.

2024-01-24 08:56 UTC, lynxnb approved these changes
Testing looks fine, the crash doesn't seem to happen anymore.
LGTM, thanks!

2024-01-24 09:02 UTC, Ishan09811 commented
> Testing looks fine, the crash doesn't seem to happen anymore. LGTM, thanks!

@lynxnb 
It means you are thinking about release in play store ? 😶

2024-01-29 16:11 UTC, merged