Add a per-game option to delete the shader cache that has been created during the emulation
strato-emu/strato pull request #249
Opened 2024-02-26 13:36 UTC by QuackingCanary

Add a per-game option to delete the shader cache that has been created

![Screenshot_20240226-143214](https://github.com/strato-emu/strato/assets/96989642/2c7f4835-1659-491d-a821-ae91c01e4f0d)

2024-02-27 10:02 UTC, lynxnb requested changes

2024-02-27 10:02 UTC, lynxnb commented on app/src/main/res/values/strings.xml
> +    <string name="delete_shader_cache_confirmation_message">Are you sure you want to clear shader cache?</string>
```suggestion
    <string name="delete_shader_cache_confirmation_message">Are you sure you want to delete all cached shaders?</string>
```

2024-02-27 13:37 UTC, Crytonics commented on app/src/main/java/org/stratoemu/strato/utils/CacheManagementUtils.kt
> +}
```suggestion
}

```
Add empty new line at the end like this

2024-03-01 14:27 UTC, lynxnb submitted a review, later dismissed

2024-03-02 17:56 UTC, PabloG02 commented on app/src/main/res/layout/app_dialog.xml
> +                android:contentDescription="@string/import_save"
```suggestion
                android:contentDescription="@string/clear_shader_cache"
```

2024-03-04 07:42 UTC, QuackingCanary commented on app/src/main/res/layout/app_dialog.xml
> +                android:contentDescription="@string/import_save"
Good catch Pablo! Thanks

2024-03-05 20:06 UTC, lynxnb approved these changes

2025-06-16 13:10 UTC, closed without merging

2025-06-16 21:38 UTC, BBlueSkyy commented
why did you delete it?

2025-09-18 23:21 UTC, Ernesto0-0 commented
Will the emulator now be able to play the cinematics that are shown in black?