Add ability to export all save files
strato-emu/strato pull request #54
Opened 2023-06-28 11:20 UTC by PabloG02

2023-07-11 11:21 UTC, 827638 commented
import android.content.pm.ShortcutInfo 
  import android.content.pm.ShortcutManager 
  import android.graphics.drawable.Icon 
 import android.net.Uri 
  import android.os.Bundle 
 import android.provider.DocumentsContract 
  import android.view.KeyEvent 
  import android.view.LayoutInflater 
  import android.view.View 
  import android.view.ViewGroup 
 import androidx.activity.result.contract.ActivityResultContracts 
  import androidx.appcompat.app.AlertDialog 
 import androidx.documentfile.provider.DocumentFile 
  import com.google.android.material.bottomsheet.BottomSheetBehavior 
  import com.google.android.material.bottomsheet.BottomSheetDialogFragment 
  import com.google.android.material.snackbar.Snackbar 
  import emu.skyline.data.AppItem 
  import emu.skyline.data.AppItemTag 
  import emu.skyline.databinding.AppDialogBinding 
  import emu.skyline.loader.LoaderResult 
 import emu.skyline.provider.DocumentsProvider 
  import emu.skyline.settings.SettingsActivity 
 import emu.skyline.utils.ZipUtils 
 import emu.skyline.utils.SaveManagementUtils 
  import emu.skyline.utils.serializable 
 import kotlinx.coroutines.CoroutineScope 
 import kotlinx.coroutines.Dispatchers 
 import kotlinx.coroutines.launch 
 import kotlinx.coroutines.withContext 
 import java.io.BufferedOutputStream 
 import java.io.File 
 import java.io.FileOutputStream 
 import java.io.FilenameFilter 
 import java.time.LocalDateTime 
 import java.time.format.DateTimeFormatter 
 import java.util.zip.ZipEntry 
 import java.util.zip.ZipOutputStream 
 
 
  /** 
   * This dialog is used to show extra game metadata and provide extra options such as pinning the game to the home screen

2023-08-07 11:53 UTC, lynxnb requested changes

2023-08-07 11:53 UTC, lynxnb commented on app/src/main/java/emu/skyline/utils/SaveManagementUtils.kt
> +        private lateinit var startForResultExportSave : ActivityResultLauncher<Intent>
These two need to be removed in favor of constructing them on demand in the corresponding import/export functions. This is unnecessary state that a static class shouldn't have, this is just like having global variables and is really error prone.

2023-08-07 11:53 UTC, lynxnb commented on app/src/main/java/emu/skyline/utils/SaveManagementUtils.kt
> +        var specificWorkUI = {}
This should be removed in favor of callbacks passed directly to the import/export functions.

2023-08-07 11:53 UTC, lynxnb commented on app/src/main/java/emu/skyline/utils/SaveManagementUtils.kt
> +                    startForResultExportSave.launch(Intent.createChooser(intent, "Share save file"))
Use a resource string here so that it can be translated.

2023-08-07 11:53 UTC, lynxnb commented on app/src/main/java/emu/skyline/utils/SaveManagementUtils.kt
> +                    val file = DocumentFile.fromSingleUri(context, DocumentsContract.buildDocumentUri(DocumentsProvider.AUTHORITY, "${DocumentsProvider.ROOT_ID}/temp/${lastZipFile.name}"))!!
You shouldn't manually build the content URI, you should use a `FileProvider` instead:
https://developer.android.com/reference/androidx/core/content/FileProvider#getUriForFile(android.content.Context,java.lang.String,java.io.File)

2023-08-07 11:53 UTC, lynxnb commented on app/src/main/java/emu/skyline/utils/SaveManagementUtils.kt
> +        private var lastZipCreated : File? = null
Ideally you shouldn't need this, you can just clear the output folder every time before exporting.

2023-08-07 22:38 UTC, PabloG02 commented on app/src/main/java/emu/skyline/utils/SaveManagementUtils.kt
> +        var specificWorkUI = {}
I'm not sure if I did it right, but it works.

2023-08-12 14:56 UTC, lynxnb commented on app/src/main/java/emu/skyline/utils/SaveManagementUtils.kt
> +        var specificWorkUI = {}
You should get rid of the `specificWorkUI` variable altogether, and instead go for passing callbacks to the various functions of the SaveManagementUtils class.
The issue I have with it is that it's not clear when and where is that callback called, it's very much hidden from the user and it could result in various lifetime bugs down the line.
You should either:
- Make the callback more specific, take a boolean as parameter and use that to do some operations, or
- Take a callback in `SaveManagementUtils.importSave` as parameter, which would result in the following usage
```kt
SaveManagementUtils.importSave(documentPicker) { importSuccessful : Boolean->
    binding.deleteSave.isEnabled = importSuccessful
    binding.exportSave.isEnabled = importSuccessful
}
```
`importSave would need to take an additional (defaulted to null) parameter of type `(Boolean) -> Unit`. The `documentPicker` object in `SaveManagementUtils` should be constructed in place in the `importSave` call rather than being saved in the class.

2023-09-06 15:03 UTC, lynxnb approved these changes
LGTM, thanks!

2023-09-06 15:03 UTC, merged