Report crash in UI by setting FPS to red
strato-emu/strato pull request #7
Opened 2023-05-10 15:48 UTC by PabloG02

2023-06-07 11:10 UTC, lynxnb commented
Rather than the FPS turning red, which might not be immediately clear to the user, I'd rather have something like a dialog or the emulator returning to the home screen with a message. I've been wanting to do something similar myself for a long time but never came around to do that. It's needs some more work but, would that be something you're interested in?

2023-06-09 12:09 UTC, PabloG02 commented
I'll try. I just did it this way because it was the least intrusive one, especially when debugging with logcat. Though I don't think returning to the home screen with a message is a good option because it would clutter the logcat.

2023-06-28 17:04 UTC, lynxnb requested changes

2023-06-28 17:04 UTC, lynxnb commented on app/src/main/cpp/skyline/kernel/types/KProcess.cpp
> +        state.jvm->reportCrash();
`Kill` is also called when the game hasn't crashed and we want to quit the game gracefully, showing a crash dialog there wouldn't make sense. You can workaround that by using the `disableCreation` parameter for now, as that is `true` only when gracefully exiting.

```suggestion
        // disableCreation is set only when gracefully exiting, it being false means an exception/crash occurred
        if (!disableCreation)
            state.jvm->reportCrash();
```

2023-07-03 11:04 UTC, lynxnb approved these changes

2023-07-03 11:26 UTC, merged